name: pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:pr-${{ github.event.pull_request.number }}
    - name: slsa verify
      id: slsa-verify
      run: |
        wget https://github.com/slsa-framework/slsa-verifier/releases/download/v2.4.1/slsa-verifier-linux-amd64
        mv slsa-verifier-linux-amd64 slsa-verifier
        chmod +x slsa-verifier
        wget https://github.com/google/go-containerregistry/releases/download/vVERSION/crane-linux-amd64
        mv crane-linux-amd64 /usr/local/bin/crane
        chmod +x /usr/local/bin/crane
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:pr-${{ github.event.pull_request.number }}
        IMAGE="${IMAGE}@"$(crane digest "${IMAGE}")
        ./slsa-verifier verify-image "$IMAGE" \
        --source-uri github.com/zoranosmanlic/github-actions-demo \
        --print-provenance 